// Derived in part from mattleong/pi-better-openai (MIT). See THIRD_PARTY_NOTICES.md.
import { readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type { ExtensionContext } from "@earendil-works/pi-coding-agent";
const agentDir = () => process.env.PI_CODING_AGENT_DIR?.trim() || join(homedir(), ".pi", "agent");
export type CodexCredentials = { accessToken: string; accountId: string; source: "modelRegistry" | "authFile" };
const record = (v: unknown): v is Record<string, unknown> => !!v && typeof v === "object" && !Array.isArray(v);
function accountFromJwt(token: string): string | undefined { try { const p = token.split(".")[1]; if (!p) return; const data: unknown = JSON.parse(Buffer.from(p.replace(/-/g, "+").replace(/_/g, "/"), "base64url").toString()); if (!record(data)) return; const auth = data["https://api.openai.com/auth"]; return record(auth) && typeof auth.chatgpt_account_id === "string" ? auth.chatgpt_account_id : undefined; } catch { return; } }
export function parseRegistryCredentials(value?: string): Omit<CodexCredentials, "source"> | undefined { const raw = value?.trim(); if (!raw) return; try { const v: unknown = JSON.parse(raw); if (record(v)) { const accessToken = typeof v.access === "string" ? v.access : typeof v.token === "string" ? v.token : undefined; const accountId = typeof v.accountId === "string" ? v.accountId : typeof v.account_id === "string" ? v.account_id : undefined; if (accessToken && accountId) return { accessToken, accountId }; } } catch {} const accountId = accountFromJwt(raw); return accountId ? { accessToken: raw, accountId } : undefined; }
export function readAuthFile(): Omit<CodexCredentials, "source"> | undefined { try { const all: unknown = JSON.parse(readFileSync(join(agentDir(), "auth.json"), "utf8")); if (!record(all) || !record(all["openai-codex"])) return; const v = all["openai-codex"] as Record<string, unknown>; const accessToken = typeof v.access === "string" ? v.access.trim() : ""; const accountId = typeof v.accountId === "string" ? v.accountId.trim() : typeof v.account_id === "string" ? v.account_id.trim() : ""; return accessToken && accountId ? { accessToken, accountId } : undefined; } catch { return; } }
export async function getCredentials(ctx: Pick<ExtensionContext, "modelRegistry">): Promise<CodexCredentials | undefined> { const raw = await ctx.modelRegistry.getApiKeyForProvider("openai-codex").catch(() => undefined); const registry = parseRegistryCredentials(raw); if (registry) return { ...registry, source: "modelRegistry" }; const file = readAuthFile(); return file ? { ...file, source: "authFile" } : undefined; }
