// Derived in part from mattleong/pi-better-openai (MIT). See THIRD_PARTY_NOTICES.md.
import { randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import type { ExtensionContext } from "@earendil-works/pi-coding-agent";
import type { ResolvedConfig } from "./config.ts";
import { getCredentials } from "./auth.ts";
const agentDir = () => process.env.PI_CODING_AGENT_DIR?.trim() || join(homedir(), ".pi", "agent");
import { sanitizeError } from "./format.ts";
export const IMAGE_URL = "https://chatgpt.com/backend-api/codex/responses";
const record = (v: unknown): v is Record<string, any> => !!v && typeof v === "object" && !Array.isArray(v);
export function buildImageRequest(prompt: string, model: string, outputFormat: string) { return { model, instructions: "", input: [{ role: "user", content: [{ type: "input_text", text: prompt }] }], tools: [{ type: "image_generation", output_format: outputFormat }], tool_choice: { type: "image_generation" }, parallel_tool_calls: false, store: false, stream: true, include: [], client_metadata: { "x-codex-installation-id": "pi-better-openai" } }; }
function imageFromEvent(v: unknown): { id: string; data: string; mimeType: string } | undefined { if (!record(v)) return; const item = record(v.item) ? v.item : v; if (item.type !== "image_generation_call" || (item.status !== undefined && item.status !== "completed")) return; const raw = typeof item.result === "string" ? item.result : typeof item.b64_json === "string" ? item.b64_json : undefined; if (!raw) return; const m = raw.match(/^data:([^;,]+);base64,(.*)$/s); return { id: typeof item.id === "string" ? item.id : randomUUID(), data: m ? m[2] : raw, mimeType: m ? m[1] : "image/png" }; }
export async function parseImageSse(response: Response, signal?: AbortSignal) { if (!response.body) throw new Error("No image response body."); const reader = response.body.getReader(), decoder = new TextDecoder(); let buffer = ""; try { while (true) { if (signal?.aborted) throw new Error("Image request cancelled."); const chunk = await reader.read(); if (chunk.done) break; buffer += decoder.decode(chunk.value, { stream: true }); let boundary = /\r?\n\r?\n/.exec(buffer); while (boundary) { const part = buffer.slice(0, boundary.index); buffer = buffer.slice(boundary.index + boundary[0].length); const payload = part.split(/\r?\n/).filter(x => x.startsWith("data:")).map(x => x.slice(5).trim()).join("\n"); if (payload && payload !== "[DONE]") { let event: unknown; try { event = JSON.parse(payload); } catch { event = undefined; } const image = imageFromEvent(event); if (image) { await reader.cancel().catch(() => undefined); return image; } if (record(event) && event.type === "response.failed") { const error = record(event.response) && record(event.response.error) ? event.response.error : record(event.error) ? event.error : undefined; throw new Error(sanitizeError(typeof error?.message === "string" ? error.message : event.message ?? "Image generation failed.")); } if (record(event) && event.type === "error") throw new Error(sanitizeError(typeof event.message === "string" ? event.message : "Image generation failed.")); } boundary = /\r?\n\r?\n/.exec(buffer); } } } finally { reader.releaseLock(); } throw new Error("No completed image was returned."); }
function extension(format: string) { return format === "jpeg" ? "jpg" : format; }
function outputDirectory(cfg: ResolvedConfig, ctx: ExtensionContext): string | undefined { if (cfg.image.defaultSave === "none") return; if (cfg.image.defaultSave === "project") return join(ctx.cwd, ".pi", "generated-images"); if (cfg.image.defaultSave === "global") return join(agentDir(), "generated-images"); const custom = cfg.image.customDirectory || process.env.PI_IMAGE_SAVE_DIR; if (!custom) throw new Error("Custom image saving requires image.customDirectory or PI_IMAGE_SAVE_DIR."); return custom.replace(/^~(?=\/)/, homedir()); }
export async function generateImage(prompt: string, ctx: ExtensionContext, cfg: ResolvedConfig, outerSignal?: AbortSignal) { if (!cfg.image.enabled) throw new Error("OpenAI image generation is disabled."); const auth = await getCredentials(ctx); if (!auth) throw new Error("Missing openai-codex OAuth credentials. Run /login openai-codex."); const model = ctx.model?.provider === "openai-codex" ? ctx.model.id : cfg.image.defaultModel; const timeout = AbortSignal.timeout(cfg.image.timeoutMs); const signal = outerSignal ? AbortSignal.any([outerSignal, timeout]) : timeout; const response = await fetch(IMAGE_URL, { method: "POST", headers: { authorization: `Bearer ${auth.accessToken}`, "chatgpt-account-id": auth.accountId, "OpenAI-Beta": "responses=experimental", accept: "text/event-stream", "content-type": "application/json", originator: "codex_cli_rs" }, body: JSON.stringify(buildImageRequest(prompt, model, cfg.image.outputFormat)), signal }); if (!response.ok) throw new Error(`OpenAI image request failed (${response.status}).`); const image = await parseImageSse(response, signal); const dir = outputDirectory(cfg, ctx); let savedPath: string | undefined; if (dir) { await mkdir(dir, { recursive: true }); savedPath = join(dir, `openai-image-${new Date().toISOString().replace(/[:.]/g, "-")}-${image.id.replace(/[^\w-]/g, "_")}.${extension(cfg.image.outputFormat)}`); await writeFile(savedPath, Buffer.from(image.data, "base64")); } return { ...image, prompt, model, outputFormat: cfg.image.outputFormat, savedPath }; }
export async function readSavedImage(path: string) { return (await readFile(path)).toString("base64"); }
