import { randomUUID } from "node:crypto";
import type { ExtensionContext } from "@earendil-works/pi-coding-agent";
import { getCredentials } from "./auth.ts";
export const RESET_CREDITS_URL = "https://chatgpt.com/backend-api/wham/rate-limit-reset-credits";
export type ResetCredit = { id: string; title?: string; status: string; resetType?: string; grantedAt?: string; expiresAt?: string; raw: Record<string, unknown> };
export type ResetCreditList = { credits: ResetCredit[]; availableCount: number };
const record = (v: unknown): v is Record<string, any> => !!v && typeof v === "object" && !Array.isArray(v);
const text = (...values: unknown[]) => values.find(v => typeof v === "string" && v.trim()) as string | undefined;
export function parseResetCredits(data: unknown): ResetCreditList { const root = record(data) ? data : {}; const values = Array.isArray(root.credits) ? root.credits : Array.isArray(root.rate_limit_reset_credits) ? root.rate_limit_reset_credits : Array.isArray(data) ? data : []; const credits = values.filter(record).map(v => ({ id: text(v.id, v.credit_id) ?? "unknown", title: text(v.title, v.name), status: text(v.status) ?? (v.redeemed ? "redeemed" : "available"), resetType: text(v.reset_type, v.scope, v.type), grantedAt: text(v.granted_at, v.grant_date, v.created_at), expiresAt: text(v.expires_at, v.expiration_date), raw: v })); const computed = credits.filter(c => c.status.toLowerCase() === "available").length; return { credits, availableCount: typeof root.available_count === "number" ? Math.max(0, root.available_count) : computed }; }
function expirationTime(value?: string): number { if (!value) return Infinity; const time = Date.parse(value); return Number.isFinite(time) ? time : Infinity; }
function formattedDate(value?: string): string | undefined { if (!value) return; const time = Date.parse(value); return Number.isFinite(time) ? new Date(time).toLocaleString() : undefined; }
export function availableCredits(list: ResetCreditList): ResetCredit[] { return list.credits.filter(c => c.status.toLowerCase() === "available").sort((a, b) => expirationTime(a.expiresAt) - expirationTime(b.expiresAt)); }
async function headers(ctx: ExtensionContext) { const auth = await getCredentials(ctx); if (!auth) throw new Error("Missing openai-codex OAuth credentials. Run /login openai-codex."); return { authorization: `Bearer ${auth.accessToken}`, "chatgpt-account-id": auth.accountId }; }
export async function fetchResetCredits(ctx: ExtensionContext, signal?: AbortSignal): Promise<ResetCreditList> { const response = await fetch(RESET_CREDITS_URL, { headers: await headers(ctx), signal }); if (!response.ok) throw new Error(`Reset-credit request failed (${response.status}).`); return parseResetCredits(await response.json()); }
export async function consumeResetCredit(ctx: ExtensionContext, creditId: string, redeemRequestId = randomUUID(), signal?: AbortSignal): Promise<{ result: string; redeemRequestId: string }> { const response = await fetch(`${RESET_CREDITS_URL}/consume`, { method: "POST", headers: { ...await headers(ctx), "content-type": "application/json" }, body: JSON.stringify({ credit_id: creditId, redeem_request_id: redeemRequestId }), signal }); if (!response.ok) throw new Error(`Reset-credit consumption failed (${response.status}).`); const data: unknown = await response.json(); const result = record(data) && typeof data.result === "string" ? data.result : record(data) && typeof data.status === "string" ? data.status : "unknown"; return { result, redeemRequestId }; }
export function formatCredits(list: ResetCreditList): string { if (!list.credits.length) return "Saved reset credits: none."; return [`Saved reset credits: ${list.availableCount} available`, ...list.credits.map(c => { const granted = formattedDate(c.grantedAt), expires = formattedDate(c.expiresAt); return [`- ${c.title ?? c.id}`, `  status: ${c.status}${c.resetType ? ` · ${c.resetType}` : ""}`, granted ? `  granted: ${granted}` : "", expires ? `  expires: ${expires}` : ""].filter(Boolean).join("\n"); })].join("\n"); }
