// Derived in part from mattleong/pi-better-openai (MIT). See THIRD_PARTY_NOTICES.md.
import type { ExtensionContext } from "@earendil-works/pi-coding-agent";
import { getCredentials } from "./auth.ts";
import { countdown, formatPercent, localReset } from "./format.ts";
export const USAGE_URL = "https://chatgpt.com/backend-api/wham/usage";
export type UsageSnapshot = { primaryRemaining: number | null; secondaryRemaining: number | null; primaryResetSeconds: number | null; secondaryResetSeconds: number | null; limited: boolean; resetCredits: number | null };
const record = (v: unknown): v is Record<string, any> => !!v && typeof v === "object" && !Array.isArray(v);
const left = (v: unknown) => typeof v === "number" && Number.isFinite(v) ? Math.max(0, Math.min(100, 100 - v)) : null;
function resetSeconds(w: unknown, now = Date.now()): number | null { if (!record(w)) return null; if (typeof w.reset_at === "number") { const ms = w.reset_at > 100_000_000_000 ? w.reset_at : w.reset_at * 1000; return Math.max(0, (ms - now) / 1000); } return typeof w.reset_after_seconds === "number" ? Math.max(0, w.reset_after_seconds) : null; }
export function parseUsage(data: unknown, now = Date.now()): UsageSnapshot { const root = record(data) ? data : {}; const bucket = record(root.rate_limit) ? root.rate_limit : {}; const p = bucket.primary_window, s = bucket.secondary_window; const credits = typeof root.available_reset_credits === "number" ? root.available_reset_credits : typeof root.rate_limit_reset_credits === "number" ? root.rate_limit_reset_credits : record(root.rate_limit_reset_credits) && typeof root.rate_limit_reset_credits.available_count === "number" ? root.rate_limit_reset_credits.available_count : null; return { primaryRemaining: left(record(p) ? p.used_percent : null), secondaryRemaining: left(record(s) ? s.used_percent : null), primaryResetSeconds: resetSeconds(p, now), secondaryResetSeconds: resetSeconds(s, now), limited: bucket.limit_reached === true || bucket.allowed === false, resetCredits: credits }; }
export async function fetchUsage(ctx: ExtensionContext, signal?: AbortSignal): Promise<UsageSnapshot> { const auth = await getCredentials(ctx); if (!auth) throw new Error("Missing openai-codex OAuth credentials. Run /login openai-codex."); const response = await fetch(USAGE_URL, { headers: { authorization: `Bearer ${auth.accessToken}`, "chatgpt-account-id": auth.accountId }, signal }); if (!response.ok) throw new Error(`OpenAI usage request failed (${response.status}).`); return parseUsage(await response.json()); }
export function compactUsage(s: UsageSnapshot, resets: boolean): string { const base = `OpenAI 5h ${formatPercent(s.primaryRemaining)} weekly ${formatPercent(s.secondaryRemaining)}`; const r = resets ? ` | resets ${countdown(s.primaryResetSeconds)}/${countdown(s.secondaryResetSeconds)}` : ""; const c = s.resetCredits === null ? "" : ` | credits ${s.resetCredits}`; return base + r + c + (s.limited ? " | limited" : ""); }
export function detailedUsage(s: UsageSnapshot): string { return [`OpenAI subscription usage`, `Primary / 5-hour: ${formatPercent(s.primaryRemaining)} remaining`, `  resets in ${countdown(s.primaryResetSeconds)} (${localReset(s.primaryResetSeconds)})`, `Secondary / weekly: ${formatPercent(s.secondaryRemaining)} remaining`, `  resets in ${countdown(s.secondaryResetSeconds)} (${localReset(s.secondaryResetSeconds)})`, `Rate limited: ${s.limited ? "yes" : "no"}`, `Saved reset credits: ${s.resetCredits ?? "unknown"}`].join("\n"); }
